site_name: Документация jethub.pro
site_url: https://docs.jethub.pro
copyright: © 2022 - с.г. jethub.pro

theme:
  name: material

  static_templates:
    - 404.html

  font:
    text: Golos Text
    code: JetBrains Mono

  favicon: assets/logo-jh-invert.png
  logo: assets/logo-jh-invert.png

  language: ru
  features:
    - announce.dismiss

    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.tabs.link

    # - header.autohide

    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest

  palette:
    scheme: slate
    primary: black
    accent: red

plugins:
  - search:
      lang:
        - en
        - ru
  - minify:
      minify_html: true
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  #     type: date
  - glightbox


extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  # social:
  #   - icon: fontawesome/brands/github
  #     link: ..
  #   - icon: fontawesome/brands/twitter
  #     link: ..

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Главная:
    - index.md
  - Python:
    - python/index.md
    - Общие:
      # - python/common_errors/error_test.md
      - Класс ВЫЗОВ ФУНКЦИИ:
          - Инъекции:
            - python/common_errors/calls/injections/JP1217C shell инъекция. Subprocess с параметром shell True.md
            - python/common_errors/calls/injections/JP1219C shell инъекция. Subprocess без параметра shell True.md
            - python/common_errors/calls/injections/JP1221C shell инъекция. Расширенный список Subprocess.md
            - python/common_errors/calls/injections/JP1223C shell инъекция через прямой вызов системной оболочки.md
          - python/common_errors/calls/JP0217C исполнение кода с помощью exec.md
          - python/common_errors/calls/JP0225С использование фиксированных строк для 'секретов' при вызове функций.md
      - Класс ОПРЕДЕЛЕНИЕ ФУНКЦИИ:
            - python/common_errors/def/JP1019F определение функции с устаревшими TLS_SSL параметрами по умолчанию.md
            - python/common_errors/def/JP0227F использование фиксированных строк для 'секретов' при опредлении функций.md
      - Класс ИМПОРТ ЗАВИСИМОСТИ:
          - python/common_errors/import/placeholder.md
      - Класс ПОИСК СТРОК:
          - python/common_errors/string/JP0221S привязка к адресу 'все интерфейсы'.md
          - python/common_errors/string/JP0223F использование фиксированных строк для переменных 'секретов'.md
          - python/common_errors/string/JP0229S небезопасное использование временных tmp файлов или директорий.md
    - Специальные:
      - Класс Blacklist Call:
          - python/special/JP0615B вызов модулей Pickle.md

