site_name: Документация jethub.pro
site_url: https://docs.jethub.pro
copyright: © 2022 - с.г. jethub.pro

theme:
  name: material

  static_templates:
    - 404.html

  font:
    text: Golos Text
    code: PT Mono

  favicon: assets/logo-jh-invert.png
  logo: assets/logo-jh-invert.png

  language: ru
  features:
    - announce.dismiss

    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.tabs.link

    # - header.autohide

    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest

  palette:
    scheme: slate
    primary: black
    accent: red

plugins:
  - search:
      lang:
        - en
        - ru
  - minify:
      minify_html: true
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  #     type: date
  - glightbox


extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  # social:
  #   - icon: fontawesome/brands/github
  #     link: ..
  #   - icon: fontawesome/brands/twitter
  #     link: ..

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Главная:
    - index.md
  - Python:
    - python/index.md
    - Общие:
      # - python/common_errors/error_test.md
      - Класс ВЫЗОВ ФУНКЦИИ:
          - Инъекции:
            - python/common_errors/calls/injections/JP1215C shell инъекция. Небезопасное использование paramiko.md
            - python/common_errors/calls/injections/JP1217C shell инъекция. Subprocess с параметром shell True.md
            - python/common_errors/calls/injections/JP1219C shell инъекция. Subprocess без параметра shell True.md
            - python/common_errors/calls/injections/JP1221C shell инъекция. Расширенный список Subprocess.md
            - python/common_errors/calls/injections/JP1223C shell инъекция через прямой вызов системной оболочки.md
            - python/common_errors/calls/injections/JP1225C shell инъекция. Subprocess без параметра shell True.md
            - python/common_errors/calls/injections/JP1227C shell инъекция. Запуск процесса с указанием относительного пути.md
            - python/common_errors/calls/injections/JP1233C shell инъекция через вызов Django extra.md
            - python/common_errors/calls/injections/JP1235C shell инъекция через вызов Django RawSQL.md
          - Библиотеки:
              - python/common_errors/calls/libs/JP0239C использование requests без таймаута.md
              - python/common_errors/calls/libs/JP0415C использование flask в режиме debug.md
              - python/common_errors/calls/libs/JP0417C вызов tarfile без проверки содержимого.md
              - python/common_errors/calls/libs/JP1025C использование yaml load.md
              - python/common_errors/calls/libs/JP1029C использование устаревшей версии библиотеки SNMP.md
              - python/common_errors/calls/libs/JP1031C использование библиотеки SNMP со слабым шифрованием.md
              - python/common_errors/calls/libs/JP1237C небезопасное использование logging с конфигурацией через listen.md
              - python/common_errors/calls/libs/JP1415C использование jinja2 с параметром autoescape False.md
              - python/common_errors/calls/libs/JP1417C использование mako без самостоятельной проверки ввода.md
              - python/common_errors/calls/libs/JP1419C вызов Django mark_safe.md
          - Протоколы SSL-TLS-SSH:
            - python/common_errors/calls/ssl_tls_ssh/JP1015C использование requests без проверки SSL сертификатов.md
            - python/common_errors/calls/ssl_tls_ssh/JP1017C вызов функции с устаревшими TLS_SSL параметрами.md
            - python/common_errors/calls/ssl_tls_ssh/JP1021C вызов функции SSL без указания TLS_SSL параметра.md
            - python/common_errors/calls/ssl_tls_ssh/JP1027C использование библиотеки paramiko для SSH-соединений без проверки ключа.md
          - python/common_errors/calls/JP0217C исполнение кода с помощью exec.md
          - python/common_errors/calls/JP0219C изменение параметров доступа к файлам через os_chmod.md
          - python/common_errors/calls/JP0225С использование фиксированных строк для «секретов» при вызове функций.md
          - python/common_errors/calls/JP0661C Использование небезопасных хэш-функций.md
          - python/common_errors/calls/JP1023C использование слабых криптографических ключей.md
          - python/common_errors/calls/JP1231C использование wildcard символа при вызове команд ОС.md
      - Класс ОПРЕДЕЛЕНИЕ ФУНКЦИИ:
          - python/common_errors/def/JP1019F определение функции с устаревшими TLS_SSL параметрами по умолчанию.md
          - python/common_errors/def/JP0227F использование фиксированных строк для «секретов» при опредлении функций.md
      - Класс ИСКЛЮЧЕНИЕ:
          - python/common_errors/exception/JP0233E блок try-except с использованием pass.md
          - python/common_errors/exception/JP0237E блок try-except с использованием continue.md
      - Класс ПОИСК СТРОК:
          - python/common_errors/string/JP0221S привязка к адресу «все интерфейсы».md
          - python/common_errors/string/JP0223S использование фиксированных строк для переменных «секретов».md
          - python/common_errors/string/JP0229S небезопасное использование временных tmp файлов или директорий.md
          - python/common_errors/string/JP1229S SQL инъекция.md
    - Специальные:
      - Класс Blacklist Call:
          - python/special/call/JP0615B вызов модулей pickle.md
          - python/special/call/JP0617B вызов модулей marshal.md
          - python/special/call/JP0619B использование небезопасных хэш функий MD2, MD4, MD5, or SHA1.md
          - python/special/call/JP0621B использование небезопасных шифров.md
          - python/special/call/JP0623B использование небезопасных шифров (режими функций).md
          - python/special/call/JP0625B использование небезопасной функции mktemp.md
          - python/special/call/JP0627B использование небезопасной функции eval.md
          - python/special/call/JP0629B использование небезопасной функции mark_safe из пакета Django.md
          - python/special/call/JP0633B использование небезопасных схем urllib urlopen.md
          - python/special/call/JP0635B использование random для криптографических операций.md
          - python/special/call/JP0637B использование telnet.md
          - python/special/call/JP0639B использование xml парсеров cElementTree.md
          - python/special/call/JP0641B использование xml парсеров ElementTree.md
          - python/special/call/JP0643B использование xml парсеров expatreader.md
          - python/special/call/JP0645B использование xml парсеров expatbuilder.md
          - python/special/call/JP0647B использование xml парсеров sax.md
          - python/special/call/JP0649B использование xml парсеров minidom.md
          - python/special/call/JP0651B использование xml парсеров pulldom.md
          - python/special/call/JP0653B использование xml парсеров etree.md
          - python/special/call/JP0655B использование протокола FTP.md
          - python/special/call/JP0657B использование протокола input python2.md
          - python/special/call/JP0659B использование ssl c unverified_context.md
      - Класс Blacklist Import:
          - python/special/import/JP0815B импорт telnetlib.md
          - python/special/import/JP0817B импорт бибилиотек FTP.md
          - python/special/import/JP0819B импорт модулей pickle.md
          - python/special/import/JP0823B импорт xml парсеров xml.etree.md
          - python/special/import/JP0825B импорт xml парсеров sax.md
          - python/special/import/JP0827B использование xml парсеров expatbuilder.md
          - python/special/import/JP0829B импорт xml парсеров minidom.md
          - python/special/import/JP0831B импорт xml парсеров pulldom.md
          - python/special/import/JP0833B импорт xml парсеров lxml.md
          - python/special/import/JP0835B импорт xmlrpc библиотек.md
          - python/special/import/JP0837B импорт httpoxy библиотек.md
          - python/special/import/JP0839B импорт библиотек crypto.md
          - python/special/import/JP0843B импорт библиотек pyghmi.md
