name: cd-stage

on:
  workflow_dispatch:
  pull_request:

env:
  PUBLISH_BRANCH: site-stage

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    permissions:
      contents: write
    environment:
      name: site-stage
      # url: https://example.stage.site

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: caching
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: image processing deps
        run: |
          sudo pip install pillow cairosvg
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          sudo apt-get install pngquant

      - name: deploy mkdocs
        run: mkdocs build -v

      - name: update publish dir to build branch
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
          publish_dir: ./site
